### ISSUE TITLE
_JAVA_OPTIONS causes Java version check error

### ISSUE THREAD

**Issue by martinstuder** [miraisolutions/xlconnect#164]
```
$  _JAVA_OPTIONS=-Xmx32000m R -e "require(XLConnect)"

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(XLConnect)
Loading required package: XLConnect
Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: javaCheck()
  error: XLConnect is compatible with Java versions 8 to 16. Detected java version: 32000
> 
```

Reason is that passing `_JAVA_OPTIONS` causes an additional line to be printed on stdout:
```
$ _JAVA_OPTIONS=-Xmx32000m R -e "require(rJava); .jinit()"

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(rJava); .jinit()
Loading required package: rJava
Picked up _JAVA_OPTIONS: -Xmx32000m
```

**Comment by martinstuder** [comment]
Looks like this was already fixed by #157

**Comment by joleyjol** [comment]
This issue seems to still exist in the most recent version available on CRAN (1.0.5).  Is there a plan to publish a new version?
